# Generated by Django 4.1.5 on 2023-01-27 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('car_location', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('rent_per_day', models.IntegerField()),
                ('availability', models.BooleanField(null=True)),
                ('about', models.TextField(blank=True, max_length=355, null=True)),
                ('arac_foto', models.ImageField(blank=True, null=True, upload_to='car_fotolari/%Y/%m/')),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('rent_per_day', models.IntegerField()),
                ('availability', models.BooleanField(null=True)),
                ('about', models.TextField(blank=True, max_length=355, null=True)),
                ('motorcycle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arac.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('rent_per_day', models.IntegerField()),
                ('availability', models.BooleanField(null=True)),
                ('about', models.TextField(blank=True, max_length=355, null=True)),
                ('bicycle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bicycle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
