# Generated by Django 4.1.5 on 2023-01-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreservation',
            name='price',
            field=models.IntegerField(default='exist'),
            preserve_default=False,
        ),
    ]
