# Generated by Django 4.1.5 on 2023-01-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arac', '0002_carreservation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreservation',
            name='price',
        ),
    ]
